import type { LocationPoint } from "@/types";

export type FishingArea = LocationPoint & {
  id: string;
  prefecture: string;
  name: string;
};

export const fishingAreas: FishingArea[] = [
  { id: "hyogo-akashi-ura", prefecture: "兵庫", name: "明石・明石浦", latitude: 34.645, longitude: 134.997 },
  { id: "hyogo-akashi-port", prefecture: "兵庫", name: "明石港", latitude: 34.646, longitude: 134.993 },
  { id: "hyogo-higashi-futami", prefecture: "兵庫", name: "明石・東二見", latitude: 34.696, longitude: 134.891 },
  { id: "hyogo-kobe-suma", prefecture: "兵庫", name: "神戸・須磨", latitude: 34.643, longitude: 135.118 },
  { id: "hyogo-kobe-maiko", prefecture: "兵庫", name: "神戸・舞子漁港", latitude: 34.633, longitude: 135.034 },
  { id: "hyogo-awaji-ikawadani", prefecture: "兵庫", name: "淡路島・育波", latitude: 34.548, longitude: 134.947 },
  { id: "hyogo-awaji-murotsu", prefecture: "兵庫", name: "淡路島・室津", latitude: 34.515, longitude: 134.899 },
  { id: "hyogo-awaji-sumoto", prefecture: "兵庫", name: "淡路島・洲本", latitude: 34.342, longitude: 134.897 },
  { id: "hyogo-awaji-yura", prefecture: "兵庫", name: "淡路島・由良", latitude: 34.282, longitude: 134.95 },
  { id: "hyogo-nishinomiya-imazu", prefecture: "兵庫", name: "西宮・今津", latitude: 34.709, longitude: 135.345 },
  { id: "hyogo-himeji-port", prefecture: "兵庫", name: "姫路港", latitude: 34.778, longitude: 134.665 },
  { id: "osaka-izumisano", prefecture: "大阪", name: "泉佐野", latitude: 34.421, longitude: 135.316 },
  { id: "osaka-izumisano-food-complex", prefecture: "大阪", name: "泉佐野食品コンビナート", latitude: 34.424, longitude: 135.302 },
  { id: "osaka-minato-shirinashi-river", prefecture: "大阪", name: "大阪市港区・尻無川", latitude: 34.658, longitude: 135.458 },
  { id: "osaka-hokko-marina", prefecture: "大阪", name: "大阪北港マリーナ", latitude: 34.673, longitude: 135.393 },
  { id: "osaka-suminoe", prefecture: "大阪", name: "住之江", latitude: 34.609, longitude: 135.442 },
  { id: "osaka-sennan-okadaura", prefecture: "大阪", name: "泉南・岡田浦新港", latitude: 34.38, longitude: 135.274 },
  { id: "osaka-sennan-ozaki", prefecture: "大阪", name: "泉南・尾崎", latitude: 34.361, longitude: 135.242 },
  { id: "osaka-sennan-kojima", prefecture: "大阪", name: "泉南・小島漁港", latitude: 34.326, longitude: 135.143 },
  { id: "osaka-sennan-tanigawa-port", prefecture: "大阪", name: "泉南・谷川港", latitude: 34.318, longitude: 135.142 },
  { id: "osaka-sennan-tarui-port", prefecture: "大阪", name: "泉南・樽井港", latitude: 34.381, longitude: 135.264 },
  { id: "osaka-senboku-tadaoka-port", prefecture: "大阪", name: "泉北・忠岡港", latitude: 34.493, longitude: 135.383 },
  { id: "osaka-sennan-tannowa", prefecture: "大阪", name: "淡輪", latitude: 34.334, longitude: 135.176 },
  { id: "osaka-nanko", prefecture: "大阪", name: "南港", latitude: 34.62, longitude: 135.417 },
  { id: "osaka-misaki-kojima", prefecture: "大阪", name: "岬町・小島", latitude: 34.325, longitude: 135.138 },
  { id: "osaka-misaki-tanagawa", prefecture: "大阪", name: "岬町・谷川港", latitude: 34.316, longitude: 135.139 },
  { id: "wakayama-kada", prefecture: "和歌山", name: "加太港", latitude: 34.277, longitude: 135.073 },
  { id: "wakayama-wakayama-port", prefecture: "和歌山", name: "和歌山港", latitude: 34.216, longitude: 135.146 },
  { id: "wakayama-wakaura", prefecture: "和歌山", name: "和歌浦港", latitude: 34.187, longitude: 135.171 },
  { id: "wakayama-saikazaki", prefecture: "和歌山", name: "雑賀崎", latitude: 34.187, longitude: 135.149 },
  { id: "wakayama-yura", prefecture: "和歌山", name: "由良", latitude: 33.956, longitude: 135.117 },
  { id: "wakayama-tanabe", prefecture: "和歌山", name: "田辺・芳養港", latitude: 33.744, longitude: 135.362 },
  { id: "wakayama-shirahama", prefecture: "和歌山", name: "白浜町・椿", latitude: 33.61, longitude: 135.397 },
  { id: "wakayama-kushimoto", prefecture: "和歌山", name: "串本", latitude: 33.472, longitude: 135.783 },
  { id: "tokushima-naruto-kameura", prefecture: "徳島", name: "鳴門亀浦", latitude: 34.241, longitude: 134.638 },
  { id: "tokushima-naruto-dounoura", prefecture: "徳島", name: "鳴門堂ノ浦", latitude: 34.237, longitude: 134.619 },
  { id: "mie-toba", prefecture: "三重", name: "鳥羽・本浦", latitude: 34.477, longitude: 136.852 },
  { id: "mie-owase", prefecture: "三重", name: "尾鷲", latitude: 34.07, longitude: 136.196 },
  { id: "mie-ago-ugata", prefecture: "三重", name: "英虞湾・鵜方", latitude: 34.328, longitude: 136.825 },
  { id: "mie-ago-goza", prefecture: "三重", name: "英虞湾・御座", latitude: 34.277, longitude: 136.765 },
  { id: "mie-oura-toba-imaura", prefecture: "三重", name: "生浦湾・鳥羽今浦", latitude: 34.507, longitude: 136.862 },
  { id: "mie-oura-toba-motoura", prefecture: "三重", name: "生浦湾・鳥羽本浦", latitude: 34.477, longitude: 136.852 },
  { id: "mie-owase-tenmaura", prefecture: "三重", name: "尾鷲・天満浦", latitude: 34.074, longitude: 136.207 },
  { id: "mie-kajika", prefecture: "三重", name: "梶賀", latitude: 33.999, longitude: 136.239 },
  { id: "mie-kata-sone", prefecture: "三重", name: "賀田湾・曽根", latitude: 33.964, longitude: 136.223 },
  { id: "mie-kamiura", prefecture: "三重", name: "神前浦", latitude: 34.218, longitude: 136.509 },
  { id: "mie-kihoku-kaino", prefecture: "三重", name: "紀北町・海野", latitude: 34.217, longitude: 136.332 },
  { id: "mie-kihoku-kiinagashima", prefecture: "三重", name: "紀北町・紀伊長島", latitude: 34.214, longitude: 136.337 },
  { id: "mie-kihoku-shimagatsuura", prefecture: "三重", name: "紀北町・島勝浦", latitude: 34.168, longitude: 136.29 },
  { id: "mie-kihoku-shiraishiko", prefecture: "三重", name: "紀北町・白石湖", latitude: 34.17, longitude: 136.245 },
  { id: "mie-kihoku-shiraura", prefecture: "三重", name: "紀北町・白浦", latitude: 34.16, longitude: 136.274 },
  { id: "mie-kihoku-higashinagashima", prefecture: "三重", name: "紀北町・東長島", latitude: 34.208, longitude: 136.343 },
  { id: "mie-kihoku-hikimoto", prefecture: "三重", name: "紀北町・引本浦", latitude: 34.134, longitude: 136.239 },
  { id: "mie-kihoku-miura", prefecture: "三重", name: "紀北町・三浦", latitude: 34.242, longitude: 136.377 },
  { id: "mie-kihoku-dose", prefecture: "三重", name: "紀北町・道瀬", latitude: 34.19, longitude: 136.303 },
  { id: "mie-kihoku-yaguchiura", prefecture: "三重", name: "紀北町・矢口浦", latitude: 34.123, longitude: 136.229 },
  { id: "mie-kumano-odomari", prefecture: "三重", name: "熊野・大泊", latitude: 33.901, longitude: 136.126 },
  { id: "mie-gokasho-nakatsuhama", prefecture: "三重", name: "五ケ所湾・中津浜", latitude: 34.345, longitude: 136.662 },
  { id: "mie-gokasho-hazamaura", prefecture: "三重", name: "五ケ所湾・迫間浦", latitude: 34.326, longitude: 136.655 },
  { id: "mie-konzasa", prefecture: "三重", name: "神津佐", latitude: 34.302, longitude: 136.649 },
  { id: "mie-sugashima-akasaki", prefecture: "三重", name: "菅島・赤崎", latitude: 34.496, longitude: 136.904 },
  { id: "mie-taiki", prefecture: "三重", name: "大紀町", latitude: 34.249, longitude: 136.423 },
  { id: "mie-taiki-nishiki", prefecture: "三重", name: "大紀町・錦", latitude: 34.209, longitude: 136.41 },
  { id: "mie-toba-akasaki", prefecture: "三重", name: "鳥羽・赤崎", latitude: 34.485, longitude: 136.856 },
  { id: "mie-toba-kuzaki", prefecture: "三重", name: "鳥羽・国崎", latitude: 34.392, longitude: 136.913 },
  { id: "mie-toba-hamabewan", prefecture: "三重", name: "鳥羽・浜辺湾", latitude: 34.47, longitude: 136.845 },
  { id: "mie-matsusaka-matsunase", prefecture: "三重", name: "松阪・松名瀬", latitude: 34.586, longitude: 136.562 },
  { id: "mie-matoya-adako", prefecture: "三重", name: "的矢湾・畔蛸", latitude: 34.37, longitude: 136.878 },
  { id: "mie-matoya-anori", prefecture: "三重", name: "的矢湾・安乗", latitude: 34.363, longitude: 136.907 },
  { id: "mie-matoya-sangasho", prefecture: "三重", name: "的矢湾・三ケ所", latitude: 34.381, longitude: 136.849 },
  { id: "mie-miura", prefecture: "三重", name: "三浦", latitude: 34.242, longitude: 136.377 },
  { id: "mie-minamiise-sazaraura", prefecture: "三重", name: "南伊勢・礫浦", latitude: 34.278, longitude: 136.69 },
  { id: "mie-minamiise-kowaura", prefecture: "三重", name: "南伊勢・古和浦", latitude: 34.226, longitude: 136.531 },
  { id: "mie-minamiise-hozaura", prefecture: "三重", name: "南伊勢町・方座浦", latitude: 34.238, longitude: 136.548 },
  { id: "kyoto-miyazu", prefecture: "京都", name: "宮津・宮津港", latitude: 35.536, longitude: 135.196 },
  { id: "kyoto-maizuru", prefecture: "京都", name: "舞鶴湾", latitude: 35.475, longitude: 135.387 },
  { id: "fukui-tsuruga", prefecture: "福井", name: "敦賀", latitude: 35.657, longitude: 136.064 },
  { id: "fukui-obama", prefecture: "福井", name: "小浜湾", latitude: 35.493, longitude: 135.746 },
  { id: "hokkaido-yoichi-kakou", prefecture: "北海道", name: "余市河口漁港", latitude: 43.206, longitude: 140.786 },
  { id: "ibaraki-oarai-port", prefecture: "茨城", name: "大洗港", latitude: 36.313, longitude: 140.584 },
  { id: "ibaraki-kashima", prefecture: "茨城", name: "鹿島", latitude: 35.941, longitude: 140.72 },
  { id: "chiba-ohara", prefecture: "千葉", name: "大原", latitude: 35.251, longitude: 140.402 },
  { id: "chiba-kominato-yoriura", prefecture: "千葉", name: "小湊寄浦", latitude: 35.12, longitude: 140.188 },
  { id: "chiba-takasaki-port", prefecture: "千葉", name: "高崎漁港", latitude: 35.099, longitude: 139.85 },
  { id: "chiba-tokawa", prefecture: "千葉", name: "外川", latitude: 35.707, longitude: 140.866 },
  { id: "kanagawa-maeguchi", prefecture: "神奈川", name: "間口", latitude: 35.151, longitude: 139.676 },
  { id: "toyama-toyama-shinko", prefecture: "富山", name: "富山市・富山新港", latitude: 36.778, longitude: 137.12 },
  { id: "shizuoka-suruga-shimizu", prefecture: "静岡", name: "駿河清水港", latitude: 35.021, longitude: 138.507 },
  { id: "shizuoka-ajiro", prefecture: "静岡", name: "網代", latitude: 35.044, longitude: 139.091 },
  { id: "aichi-katana", prefecture: "愛知", name: "片名", latitude: 34.711, longitude: 136.973 },
  { id: "aichi-morozaki", prefecture: "愛知", name: "師崎", latitude: 34.704, longitude: 136.966 },
  { id: "aichi-yamami", prefecture: "愛知", name: "山海", latitude: 34.739, longitude: 136.868 },
  { id: "shiga-otsu-kiwagawa", prefecture: "滋賀", name: "大津・際川", latitude: 35.036, longitude: 135.86 },
  { id: "fukui-echizen-shuku", prefecture: "福井", name: "越前町・宿", latitude: 35.968, longitude: 135.962 },
  { id: "fukui-mihama-hayase", prefecture: "福井", name: "美浜・早瀬", latitude: 35.602, longitude: 135.911 },
  { id: "fukui-echizen-umeura", prefecture: "福井", name: "越前町・梅浦漁港", latitude: 35.965, longitude: 135.951 },
  { id: "fukui-echizen-ocho", prefecture: "福井", name: "越前町・大樟漁港", latitude: 35.947, longitude: 135.939 },
  { id: "fukui-uchiura-otoomi", prefecture: "福井", name: "内浦湾・音海", latitude: 35.543, longitude: 135.525 },
  { id: "fukui-uchiura-kounoura", prefecture: "福井", name: "内浦湾・神野浦", latitude: 35.531, longitude: 135.545 },
  { id: "fukui-uchiura-hibi", prefecture: "福井", name: "内浦湾・日引", latitude: 35.526, longitude: 135.574 },
  { id: "fukui-echizen-shirahama", prefecture: "福井", name: "越前町・白浜漁港", latitude: 35.931, longitude: 135.933 },
  { id: "fukui-obama-ugu", prefecture: "福井", name: "小浜・宇久", latitude: 35.526, longitude: 135.682 },
  { id: "fukui-obama-oshima-kawamura", prefecture: "福井", name: "小浜湾・大島河村", latitude: 35.526, longitude: 135.643 },
  { id: "fukui-obama-oshima-nishimura", prefecture: "福井", name: "小浜湾・大島西村", latitude: 35.518, longitude: 135.635 },
  { id: "fukui-obama-oshima-hatamura", prefecture: "福井", name: "小浜湾・大島畑村", latitude: 35.512, longitude: 135.626 },
  { id: "fukui-obama-old-port", prefecture: "福井", name: "小浜湾・小浜旧港", latitude: 35.502, longitude: 135.745 },
  { id: "fukui-obama-new-port", prefecture: "福井", name: "小浜湾・小浜新港", latitude: 35.496, longitude: 135.737 },
  { id: "fukui-obama-katami", prefecture: "福井", name: "堅海", latitude: 35.492, longitude: 135.784 },
  { id: "fukui-obama-kogasaki", prefecture: "福井", name: "小浜湾・甲ケ崎", latitude: 35.486, longitude: 135.77 },
  { id: "fukui-obama-tomari", prefecture: "福井", name: "小浜湾・泊", latitude: 35.545, longitude: 135.672 },
  { id: "fukui-obama-nishizu", prefecture: "福井", name: "小浜湾・西津", latitude: 35.5, longitude: 135.759 },
  { id: "fukui-obama-hotokegaya", prefecture: "福井", name: "小浜湾・仏谷", latitude: 35.498, longitude: 135.686 },
  { id: "fukui-obama-wakasahongo", prefecture: "福井", name: "小浜湾・若狭本郷", latitude: 35.491, longitude: 135.615 },
  { id: "fukui-sakai-mikuni", prefecture: "福井", name: "坂井市・三国港", latitude: 36.219, longitude: 136.139 },
  { id: "fukui-takahama-wada", prefecture: "福井", name: "高浜町・和田港", latitude: 35.489, longitude: 135.556 },
  { id: "fukui-tsuruga-irohama", prefecture: "福井", name: "敦賀・色浜", latitude: 35.716, longitude: 136.049 },
  { id: "fukui-tsuruga-te", prefecture: "福井", name: "敦賀・手", latitude: 35.733, longitude: 136.055 },
  { id: "fukui-tsuruga-nago", prefecture: "福井", name: "敦賀・名子", latitude: 35.712, longitude: 136.018 },
  { id: "fukui-tsuruga-nouma", prefecture: "福井", name: "敦賀・縄間", latitude: 35.684, longitude: 136.0 },
  { id: "fukui-fukui-gushizaki", prefecture: "福井", name: "福井市・茱崎港", latitude: 36.035, longitude: 135.976 },
  { id: "fukui-mihama-hirugako", prefecture: "福井", name: "美浜・日向湖", latitude: 35.607, longitude: 135.919 },
  { id: "kyoto-kyotango-asamogawa", prefecture: "京都", name: "京丹後・浅茂川漁港", latitude: 35.689, longitude: 135.035 },
  { id: "kyoto-kyotango-kumihama-minatomiya", prefecture: "京都", name: "京丹後・久美浜湊宮", latitude: 35.629, longitude: 134.895 },
  { id: "kyoto-maizuru-isazu-left", prefecture: "京都", name: "西舞鶴・伊佐津川左岸", latitude: 35.446, longitude: 135.326 },
  { id: "kyoto-maizuru-gyokyo", prefecture: "京都", name: "西舞鶴・漁協手前", latitude: 35.455, longitude: 135.33 },
  { id: "kyoto-maizuru-takano-left", prefecture: "京都", name: "西舞鶴・高野川左岸", latitude: 35.445, longitude: 135.322 },
  { id: "kyoto-maizuru-nohara", prefecture: "京都", name: "舞鶴・野原", latitude: 35.582, longitude: 135.475 },
  { id: "kyoto-maizuru-kamisabagah", prefecture: "京都", name: "舞鶴湾・上佐波賀", latitude: 35.513, longitude: 135.397 },
  { id: "kyoto-maizuru-shimosabagah", prefecture: "京都", name: "舞鶴湾・下佐波賀", latitude: 35.507, longitude: 135.405 },
  { id: "kyoto-miyazu-shimakage", prefecture: "京都", name: "宮津・島陰", latitude: 35.585, longitude: 135.206 },
  { id: "kyoto-miyazu-haji", prefecture: "京都", name: "宮津・波路", latitude: 35.539, longitude: 135.2 },
  { id: "kyoto-miyazu-satohami", prefecture: "京都", name: "宮津・里波見", latitude: 35.594, longitude: 135.242 },
  { id: "kyoto-miyazu-yoro-oshima", prefecture: "京都", name: "宮津・養老大島", latitude: 35.654, longitude: 135.229 },
  { id: "hyogo-aioi-sakuma-marina", prefecture: "兵庫", name: "相生・サクママリーナ", latitude: 34.78, longitude: 134.466 },
  { id: "hyogo-awaji-ikuho", prefecture: "兵庫", name: "淡路島・生穂", latitude: 34.438, longitude: 134.932 },
  { id: "hyogo-awaji-shiota", prefecture: "兵庫", name: "淡路島・塩田", latitude: 34.396, longitude: 134.83 },
  { id: "hyogo-kobe-sumaura", prefecture: "兵庫", name: "神戸・須磨浦", latitude: 34.637, longitude: 135.1 },
  { id: "hyogo-takasago", prefecture: "兵庫", name: "高砂", latitude: 34.748, longitude: 134.787 },
  { id: "hyogo-toyooka-tsuiyama-kehi", prefecture: "兵庫", name: "豊岡市・津居山気比", latitude: 35.657, longitude: 134.82 },
  { id: "hyogo-hayashizaki", prefecture: "兵庫", name: "林崎", latitude: 34.649, longitude: 134.965 },
  { id: "hyogo-himeji", prefecture: "兵庫", name: "姫路", latitude: 34.78, longitude: 134.674 },
  { id: "hyogo-ichibori-river", prefecture: "兵庫", name: "市堀川", latitude: 34.704, longitude: 135.171 },
  { id: "wakayama-inami-port", prefecture: "和歌山", name: "印南港", latitude: 33.818, longitude: 135.221 },
  { id: "wakayama-kainan", prefecture: "和歌山", name: "海南", latitude: 34.152, longitude: 135.201 },
  { id: "wakayama-kushimoto-oshima", prefecture: "和歌山", name: "串本町・大島", latitude: 33.474, longitude: 135.821 },
  { id: "wakayama-kushimoto-kushimoto-oshima", prefecture: "和歌山", name: "串本町・串本大島", latitude: 33.47, longitude: 135.823 },
  { id: "wakayama-kushimoto-port", prefecture: "和歌山", name: "串本町・串本港", latitude: 33.472, longitude: 135.781 },
  { id: "wakayama-kushimoto-fukuro", prefecture: "和歌山", name: "串本町・袋", latitude: 33.461, longitude: 135.751 },
  { id: "wakayama-kushimoto-tanami", prefecture: "和歌山", name: "串本町・田並", latitude: 33.49, longitude: 135.687 },
  { id: "wakayama-kushimoto-wabuka-azashi", prefecture: "和歌山", name: "串本町・和深・安指漁港", latitude: 33.507, longitude: 135.615 },
  { id: "wakayama-shimotsu-yuasa", prefecture: "和歌山", name: "下津・湯浅", latitude: 34.032, longitude: 135.177 },
  { id: "wakayama-shirahama-ichie", prefecture: "和歌山", name: "白浜町・市江漁港", latitude: 33.641, longitude: 135.336 },
  { id: "wakayama-shirahama-tondaura", prefecture: "和歌山", name: "白浜町・富田浦袋港", latitude: 33.64, longitude: 135.39 },
  { id: "wakayama-shirahama-hikigawa", prefecture: "和歌山", name: "白浜町・日置川尻", latitude: 33.555, longitude: 135.439 },
  { id: "wakayama-susami-port", prefecture: "和歌山", name: "すさみ町・すさみ港", latitude: 33.549, longitude: 135.497 },
  { id: "wakayama-susami-mirozu", prefecture: "和歌山", name: "すさみ町・見老津漁港", latitude: 33.509, longitude: 135.58 },
  { id: "wakayama-nachikatsuura-uragami", prefecture: "和歌山", name: "那智勝浦町・浦神港", latitude: 33.561, longitude: 135.905 },
  { id: "wakayama-nishiwaki", prefecture: "和歌山", name: "西脇", latitude: 34.263, longitude: 135.096 },
  { id: "wakayama-hidaka-kashiwa", prefecture: "和歌山", name: "日高町・柏", latitude: 33.91, longitude: 135.075 },
  { id: "wakayama-hinomisaki-mio", prefecture: "和歌山", name: "日ノ岬・三尾港", latitude: 33.884, longitude: 135.063 },
  { id: "wakayama-miogawa", prefecture: "和歌山", name: "三尾川", latitude: 33.548, longitude: 135.595 },
  { id: "wakayama-minabe-sakai", prefecture: "和歌山", name: "みなべ・堺", latitude: 33.759, longitude: 135.318 },
  { id: "wakayama-minabe-sakainishi", prefecture: "和歌山", name: "みなべ町・堺西港", latitude: 33.758, longitude: 135.311 },
  { id: "wakayama-mihama-port", prefecture: "和歌山", name: "美浜町・美浜港", latitude: 33.888, longitude: 135.152 },
  { id: "wakayama-yuasa-suhara", prefecture: "和歌山", name: "湯浅町・栖原", latitude: 34.025, longitude: 135.159 },
  { id: "wakayama-yuasa-hiro", prefecture: "和歌山", name: "湯浅・広港", latitude: 34.028, longitude: 135.16 },
  { id: "wakayama-yura-obiki", prefecture: "和歌山", name: "由良町・大引", latitude: 33.954, longitude: 135.069 },
  { id: "wakayama-yura-kamiya", prefecture: "和歌山", name: "由良町・神谷", latitude: 33.971, longitude: 135.086 },
  { id: "wakayama-wakayama-city", prefecture: "和歌山", name: "和歌山市内", latitude: 34.231, longitude: 135.17 },
  { id: "tokushima-anan-nakaura", prefecture: "徳島", name: "阿南中浦緑地", latitude: 33.921, longitude: 134.681 },
  { id: "tokushima-anan-nakabayashi", prefecture: "徳島", name: "阿南・中林漁港", latitude: 33.904, longitude: 134.708 },
  { id: "tottori-sakaiminato-nakano", prefecture: "鳥取", name: "境港・中野港", latitude: 35.539, longitude: 133.244 },
  { id: "tottori-karo-port", prefecture: "鳥取", name: "鳥取港（賀露港）", latitude: 35.543, longitude: 134.181 },
  { id: "tottori-natsudomari", prefecture: "鳥取", name: "鳥取・夏泊漁港", latitude: 35.512, longitude: 134.019 },
  { id: "ehime-misho", prefecture: "愛媛", name: "御荘", latitude: 32.958, longitude: 132.57 },
  { id: "kochi-ashizuri-isa", prefecture: "高知", name: "足摺岬伊佐漁港", latitude: 32.724, longitude: 133.013 },
  { id: "kochi-muroto-kiragawa", prefecture: "高知", name: "室戸吉良川町", latitude: 33.287, longitude: 134.148 },
  { id: "kochi-muroto-cape", prefecture: "高知", name: "室戸岬", latitude: 33.245, longitude: 134.177 },
  { id: "fukuoka-itoshima-himeshima", prefecture: "福岡", name: "糸島・姫島", latitude: 33.57, longitude: 130.046 },
  { id: "fukuoka-itoshima-funakoshi", prefecture: "福岡", name: "糸島・船越", latitude: 33.582, longitude: 130.153 },
  { id: "fukuoka-hakata", prefecture: "福岡", name: "博多", latitude: 33.606, longitude: 130.403 },
  { id: "fukuoka-hakata-funadamari", prefecture: "福岡", name: "博多船溜（中央区港町）／かもめ広場前", latitude: 33.602, longitude: 130.391 },
  { id: "fukuoka-munakata-jinoshima", prefecture: "福岡", name: "宗像地島（鐘崎港）", latitude: 33.877, longitude: 130.529 },
  { id: "saga-yobuko", prefecture: "佐賀", name: "呼子", latitude: 33.544, longitude: 129.895 },
  { id: "saga-yobuko-kabeshima", prefecture: "佐賀", name: "呼子・加部島", latitude: 33.565, longitude: 129.883 }
];

export function getFishingAreaById(id: string) {
  return fishingAreas.find((area) => area.id === id) ?? null;
}

export function groupedFishingAreas() {
  return fishingAreas.reduce<Record<string, FishingArea[]>>((groups, area) => {
    groups[area.prefecture] = [...(groups[area.prefecture] ?? []), area];
    return groups;
  }, {});
}
